parent_config: "config/default.yaml"
config_filename: "copying_memory.yaml"
description: "copying memory task"

project_name: "copying_memory_task"
ex_name: "ex06"

#01 rnn
#02 rnn + layernorm
#03 rnn + idenity
#04 rnn + layer + idenity

# model specific details

model:  "RNN"
input_size: 10
output_size:  9
num_layers: 1
layer_size: [80]
activation: "relu"
layer_norm: True  # works only for LSTM, RNN
identity_init: True # works only for RNN

# optimization specific details

# Valid optimizer names: Adadelta, Adagrad, Adam, RMSprop, SGD
optim_name: "Adam"
lr: 1.0e-3
rho: 0.9
eps:  1.0e-8
weight_decay: 0.0
lr_decay: 0.0
beta_0: 0.9
beta_1: 0.999
alpha:  0.99
momentum: 0.0
centered: False
dampening:  0.0
nesterov: False
grad_clip_norm:  5.0

max_steps:  100000000
rseed:  5
device: "cuda:1" # can be cpu or cuda or cuda:1, cuda:2

# task specific details
task: "copying_memory"
batch_size: 10
seed: 5
time_lag: 100
seq_len: 10

# saving details
use_tflogger: True
save_every_n: 1000
inter_saving: [0, 1000, 2000, 3000, 4000, 5000]
