config_filename: "toy.yaml"
description: "seq2seq opus"
project_name: "seq2seq_opus"
ex_name: "opus_seq2seq"
base_data_path: "/mnt/data/chinna/data/OpenSubData/"
num_dialogs: 100 # valid ones are 100, 1000, 200000, 500000

# Model details
emb_size_src: 512
hidden_dim_src: 1024
hidden_dim_tgt: 1024
bidirectional: False
nlayers_src: 1
nlayers_tgt: 1

# Dataset specific details
eou: "<eou>"
go: "<go>"
unk: "<unk>"
num: "<num>"
pad: "<pad>"
sentence_len_cut_off: 15
min_sent_len: 6
train_valid_split: 0.50

# Valid optimizer names: Adadelta, Adagrad, Adam, RMSprop, SGD  
optim_name: "Adam"
lr: 1.0e-3
rho: 0.9
eps:  1.0e-8
weight_decay: 0.0
lr_decay: 0.0
beta_0: 0.9                                                                                                                   
beta_1: 0.999
alpha:  0.99
momentum: 0.0
centered: False
dampening:  0.0
nesterov: False
grad_clip_norm: 5.0

# task specific details
device: "cuda"
num_epochs: 200
batch_size: 20
task: "opus_lm"
eval_batch_size: 32
test_batch_size: 32
rseed: 5
time_lag: 100
seq_len: 10
bptt: 70

# saving details
use_tflogger: True
save_every_n: 500
inter_saving: [0, 1000, 2000, 3000, 4000, 5000]
