config_filename: "default.yaml"
description: "Default LSTM model for copy task"

project_name: "copy_task"
ex_name: "ex01"

# model specific details

model:  "LSTM"
input_size: 8
output_size:  8
num_layers: 1
layer_size: [256]
activation: "tanh"

# optimization specific details

# Valid optimizer names: Adadelta, Adagrad, Adam, RMSprop, SGD
optim_name: "Adam"
lr: 1.0e-3
rho: 0.9
eps:  1.0e-8
weight_decay: 0.0
lr_decay: 0.0
beta_0: 0.9
beta_1: 0.999
alpha:  0.99
momentum: 0.0
centered: False
dampening:  0.0
nesterov: False
grad_clip:  [-10.0, 10.0]

max_steps:  100000000
rseed:  5
device: "cuda" # can be cpu or cuda or cuda:1, cuda:2


# task specific details
task: "copy"
num_bits: 8
seq_len: 5
batch_size: 10

# curriculum related details
min_seq_len:  5
max_seq_len:  11
step_seq_len: 2
average_over_last_n: 10
evaluate_over_n: 10
curriculum_seed: 6

# early stopping related details
time_span: 100

# Details related to expanding the rnn
expanded_layer_size: [256]
make_optimizer_wider: True

# saving details
use_tflogger: True
save_every_n: 10000