python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 1
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 2
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 3
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 4
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 5
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 6
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 7
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 8
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 9
python construct_state_agg_replay_buffer.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 10
