python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 12
python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 13
python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 14
python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 15
python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 16
python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 17
python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 18
python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 19
python train_mdp.py --base_dir save_dir_py04/ --exp_desc 80_percent --run_num 20
