config_filename: "ptb.yaml"
description: "character langauge model ptb"

project_name: "char_language_model_ptb"
ex_name: "fm_mul_smgd_150"
data: "data/pennchar"

# model specific details

model:  "FlatMemory"
input_emb_size: 200
num_layers: 1
layer_size: [1000]
activation: "tanh"
use_relu: True
chrono_init: False
layer_norm: False
memory_size: 576
k: 4

# optimization specific details

# Valid optimizer names: Adadelta, Adagrad, Adam, RMSprop, SGD
optim_name: "Adam"
lr: 1.0e-3
rho: 0.9
eps:  1.0e-8
weight_decay: 0.0
lr_decay: 0.0
beta_0: 0.9
beta_1: 0.999
alpha:  0.99
momentum: 0.0
centered: False
dampening:  0.0
nesterov: False
grad_clip_norm: 5.0

max_steps: 200000
num_epochs: 20
rseed:  5
device: "cuda:0" # can be cpu or cuda or cuda:1, cuda:2

# task specific details
task: "char_lm_ptb"
batch_size: 128
eval_batch_size: 128
test_batch_size: 128
seed: 5
bptt: 150

# saving details
use_tflogger: True
save_every_n: 1000
inter_saving: [0, 1000, 2000, 3000, 4000, 5000]
