config_filename: "enwiki8.yaml"
description: "character langauge model enwiki8"

project_name: "char_language_model_enwiki8"
ex_name: "char_lm_enwiki8_janet"
data: "data/enwik8"

# model specific details
model:  "JANET"
num_layers: 1
layer_size: [930]
activation: "relu"
layer_norm: False
chrono_init: True
input_emb_size: 200

# optimization specific details

# Valid optimizer names: Adadelta, Adagrad, Adam, RMSprop, SGD
optim_name: "Adam"
lr: 1.0e-3
rho: 0.9
eps:  1.0e-8
weight_decay: 0.0
lr_decay: 0.0
beta_0: 0.9
beta_1: 0.999
alpha:  0.99
momentum: 0.0
centered: False
dampening:  0.0
nesterov: False
grad_clip_norm: 5.0

max_steps: 200000
num_epochs: 20
rseed:  5
device: "cuda:1" # can be cpu or cuda or cuda:1, cuda:2

# task specific details
task: "char_lm_enwiki8"
batch_size: 128
eval_batch_size: 128
test_batch_size: 128
seed: 5
time_lag: 100
seq_len: 10
bptt: 150

# saving details
use_tflogger: True
save_every_n: 1000
inter_saving: [0, 1000, 2000, 3000, 4000, 5000]
